= infra-lib
David Dreggors <david.dreggors@redhat.com>; Vinny Valdez <vvaldez@redhat.com>; Ales Nosek <anosek@redhat.com>

This repo contains a custom collection for deploying OpenShift, ArgoCD, and it clones a gitops repo that is used to deploy day 2 operations and applications in ArgoCD Applications.
In the gitops repo the manifests directory is for Kustomize manifests and charts directory will contain helm charts, both of which ArgoCD will use to deploy Applications.
By using Kustomize alongside Helm we can demonstrate the power and flexibility of ArgoCD.

These repos are a refactor of Jason Horn's original gitops work which can be found at https://github.com/hornjason/argocd-lab

== Getting set up

=== The variables

The main variables file under `inventory/group_vars/provisioner` has all requires keys and default or example values where possible. Use this as a guide to start getting familiar with the required variables.

There are 3 main variable groups...

.Variable Groups
|===
|Variable Group |Description

|Main vars
|The main variables used determine pathing, git repositories, and branches used to setup manifests and charts for later gitops tasks.

|Cluster vars
|The variables that contain the information used to define and deploy your cluster

|VCenter vars
|The variables that contain credentials and connection details for vCenter
|===

For a details on indivdual variables see the link:docs/param_list.adoc[Variable Documentation]


=== Inventory

The inventory file (named `hosts.yml`) located under the `inventory` folder defines the details of how to connect to your provioning host.

== Running the playbook

----
ansible-playbook -i inventory/hosts.yml deploy.yml
----
