---
- name: Deploy ArgoCD CR
  environment:
    K8S_AUTH_KUBECONFIG: "{{ cluster_kubeconfig }}"
  community.kubernetes.k8s:
    state: present
    wait: yes
    definition: "{{ lookup('file', '{{ manifest_dir }}/argocd/argocd-operator/example-argocd-cr.yaml') | from_yaml }}"

- name: Wait for ArgoCD CR to be available
  environment:
    K8S_AUTH_KUBECONFIG: "{{ cluster_kubeconfig }}"
  community.kubernetes.k8s_info:
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: argocds.argoproj.io
    wait: True
    wait_condition:
      reason: 'NoConflicts'
      status: 'True'
      type: 'NamesAccepted'
  register: argocds_crd

- name: Deploy ArgoCD Lab Configuration
  environment:
    K8S_AUTH_KUBECONFIG: "{{ cluster_kubeconfig }}"
  community.kubernetes.k8s:
    state: present
    wait: yes
    definition: "{{ lookup('file', '{{ manifest_dir }}/argocd/overlays/lab/argocd-app-argocd.yaml') | from_yaml }}"
...
